### ISSUE TITLE
1.8.0 breaks: No rule to make target 'sphere-quad.h', needed by 'all'.  Stop.

### ISSUE THREAD

**Issue by yurivict** [NanoComp/mpb#101] opened 2019-05-04 02:28 UTC
```
gmake[2]: Entering directory '/usr/ports/science/mpb/work/mpb-1.8.0'
gmake  all-recursive
gmake[3]: Entering directory '/usr/ports/science/mpb/work/mpb-1.8.0'
Making all in src
gmake[4]: Entering directory '/usr/ports/science/mpb/work/mpb-1.8.0/src'
cp -f mpbconf.h mpb.h
gmake  all-recursive
gmake[5]: Entering directory '/usr/ports/science/mpb/work/mpb-1.8.0/src'
Making all in util
gmake[6]: Entering directory '/usr/ports/science/mpb/work/mpb-1.8.0/src/util'
gmake[6]: *** No rule to make target 'sphere-quad.h', needed by 'all'.  Stop.
gmake[6]: Leaving directory '/usr/ports/science/mpb/work/mpb-1.8.0/src/util'
```

FreeBSD 11.2

**Comment by stevengj** [comment] 2019-05-04 02:36
Duplicate of #82, see the solution there.

**Closed by stevengj** 2019-05-04 02:36 UTC

**Comment by yurivict** [comment] 2019-05-04 02:49
The suggested workaround
```
sh autogen.sh
make
```
fails:
```
gmake[2]: Makefile: No such file or directory
gmake[2]: *** No rule to make target 'Makefile'.  Stop.
```

**Comment by yurivict** [comment] 2019-05-04 02:49
calling configure leads to the same error.

**Comment by stevengj** [comment] 2019-05-04 03:04
Does `sh autogen.sh` give an error that you ignored?  Maybe you don't have `autoconf`, `automake`, and `libtool` installed.

In general, you need special tools like autoconf and swig installed if you want to build from the git repo.  For ordinary users I would recommend installing from the `.tar.gz` official releases at https://github.com/NanoComp/mpb/releases instead.

**Comment by yurivict** [comment] 2019-05-04 03:06
No, they are all present. I use the FreeBSD ports framework, it provides everything.

**Comment by yurivict** [comment] 2019-05-04 03:10
No errors/warnings from autoconf.
I can't use taballs, FreeBSD pramework doesn't allow tarballs from github. It directs to use source.
